# Site settings
title: LOW LEVEL MAGIC
email: contact@lowlevelmagic.dev
formspree_id: <%= ENV['FORMSPREE_ID'] || 'xpwaeqkb' %>
description: >-
  We build AI characters with soul and experiences that survive the real world.
  Partner with Low Level Magic to create unforgettable, production-ready AI for your next project.
baseurl: "/llmagic"
url: "https://estiens.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
# theme: low-level-magic-theme

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  practices:
    output: true
    permalink: /:collection/:name/
  labs:
    output: true
    permalink: /:collection/:name/
  case_studies:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "practices"
    values:
      layout: "practice"
  - scope:
      path: ""
      type: "labs"
    values:
      layout: "lab"
  - scope:
      path: ""
      type: "case_studies"
    values:
      layout: "case_study"

# Site configuration
author:
  name: LOW LEVEL MAGIC Team
  email: contact@lowlevelmagic.dev

# Social links
social:
  github: lowlevelmagic
  linkedin: lowlevelmagic
  twitter: lowlevelmagic

# Navigation
navigation:
  - title: Projects
    url: /#work
  - title: Experiments
    url: /labs/
  - title: Tools
    url: /practices/
  - title: Manifestos
    url: /manifestos/
  - title: Contact
    url: /#contact
  - title: Links
    url: /links/

# Keep generated files during build
keep_files:
  - assets

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.txt
  - package.json
  - package-lock.json
  - yarn.lock
  - tailwind.config.js
  - postcss.config.js
  - assets/css/tailwind.css
  - _config_dev.yml
  - "*.bak"
