# Site settings
title: LOW LEVEL MAGIC
email: contact@artizan.dev
formspree_id: xpwaeqkb
description: >-
  We build AI characters with soul and experiences that survive the real world.
  Partner with Low Level Magic to create unforgettable, production-ready AI for your next project.
baseurl: ""
url: "https://artizan.dev"

# Build settings
markdown: kramdown
highlighter: rouge
theme: low-level-magic-theme

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  practices:
    output: true
    permalink: /:collection/:name/
  labs:
    output: true
    permalink: /:collection/:name/
  case_studies:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "practices"
    values:
      layout: "practice"
  - scope:
      path: ""
      type: "labs"
    values:
      layout: "lab"
  - scope:
      path: ""
      type: "case_studies"
    values:
      layout: "case_study"

# Site configuration
author:
  name: LOW LEVEL MAGIC Team
  email: contact@artizan.dev

# Social links
social:
  github: artizan
  linkedin: artizan
  twitter: artizan

# Navigation
navigation:
  - title: About
    url: /#about
  - title: Projects
    url: /case-studies/
  - title: Experiments
    url: /labs/
  - title: Tools
    url: /practices/
  - title: Manifestos
    url: /manifestos/
  - title: Contact
    url: /#contact

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.txt
